name: Qodana
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - develop
  push:
    branches:
      - master
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  qodana:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    permissions:
      contents: read
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Generate sources
        run: ./gradlew :app:openApiGenerateEvents :app:openApiGenerateStands
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2026.2
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          use-caches: true
          pr-mode: false
          post-pr-comment: true
          use-annotations: true
